namespace: gvm

clusterDomain: cluster.local

feed:
  fsGroup: 1000
  fsGroupChangePolicy: OnRootMismatch
  init:
    image: busybox:1.36
  rsyncTempDir: /tmp
  image:
    repository: ozgenm/feed-img
    tag: latest
    pullPolicy: IfNotPresent
  tz: "Europe/Berlin"
  pvc:
    plugins: { name: gvm-plugins-pvc, size: 5Gi }
    notus: { name: gvm-notus-pvc,   size: 2Gi }
    logs: { name: gvm-log-pvc,     size: 1Gi }
  readiness:
    initialDelaySeconds: 10
    periodSeconds: 30
    timeoutSeconds: 5
    failureThreshold: 10
  liveness:
    initialDelaySeconds: 60
    periodSeconds: 60

scanner:
  image:
    repository: ozgenm/scanner
    tag: latest
    pullPolicy: IfNotPresent
  service:
    name: openvas-service
    port: 3001
    type: ClusterIP
  hostNetwork: true
  saName: openvas

# Optional if you pull from a private registry
imagePullSecrets: [ ]

redis:
  config: |-
    bind 127.0.0.1
    protected-mode yes
    port 0
    tcp-backlog 511
    unixsocket /run/redis/redis.sock
    unixsocketperm 777
    timeout 0
    tcp-keepalive 300
    supervised no
    pidfile /run/redis/redis-server.pid
    loglevel notice
    syslog-enabled yes
    databases 1025
    save ""
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir ./
    slave-serve-stale-data yes
    slave-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    slave-priority 100
    maxclients 10000
    appendonly no
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no

    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    lua-time-limit 5000
    
    slowlog-log-slower-than 10000
    
    slowlog-max-len 128
    
    latency-monitor-threshold 0
    notify-keyspace-events ""
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    aof-rewrite-incremental-fsync yes

# --- Postgres subchart (optional) ---
postgresql:
  enabled: true
  architecture: standalone
  auth:
    username: "gvmd"         # app user
    password: "gvmdpw"       # or leave empty to auto-generate
    database: "gvmd-lite-service"
  primary:
    persistence:
      enabled: true
      size: 8Gi

gvmdLite:
  image:
    repository: ozgenm/gvmd-lite
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "200m"
      memory: "500Mi"
    limits:
      cpu: "1"
      memory: "2Gi"
  service:
    name: gvmd-lite
    port: 8082
    type: ClusterIP
  pvcPluginsName: gvm-plugins-pvc

  # Use **external** DB instead of the Bitnami subchart when enabled:
  externalDb:
    enabled: false
    host: "postgres.external.svc"
    port: 5432
    user: "user"
    name: "gvmd-lite-service"
    passwordSecretName: ""      # e.g., my-external-pg
    passwordSecretKey: "DB_PASSWORD"

  # App-only secrets (not DB):
  secrets:
    ADMIN_PASSWORD: "admin"
    JWT_SECRET: "your-super-secret-key"
    CREDENTIAL_ENCRYPTION_KEY: "V1cyVHd3M2FpVmZXWjBFUWdnRmU2OU4wQzBxUFR4VEc="

    # Application env configuration
  env:
    JWT_TOKEN_TIME: "2"            # hours
    REFRESH_TOKEN_TIME: "1"        # days
    ENABLE_CVSS3_1: "1"
    FEED_VT_METADATA_PATH: "/var/lib/openvas/plugins/vt-metadata.json"
    FEED_SCAN_CONFIG_DIR: ""
    LOG_LEVEL: "info"
