name: helm-lint

on:
  pull_request:
    paths:
      - "charts/**"
      - "Makefile"
      - ".github/workflows/helm-lint.yaml"
  push:
    branches: [ main ]
    paths:
      - "charts/**"
      - "Makefile"
      - ".github/workflows/helm-lint.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.13.1

      - name: Helm lint
        run: make lint
