name: helm-tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup Helm
        uses: azure/setup-helm@v5.0.1
        with:
          version: v3.19.3

      - name: Build dependencies
        run: helm dependency build charts/gvm-lite-stack

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Unit tests
        run: make test
