name: helm-tests

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.13.1

      - name: Build dependencies
        run: helm dependency build charts/gvm-lite-stack

      - name: Install helm-unittest
        run: helm plugin install https://github.com/helm-unittest/helm-unittest

      - name: Unit tests
        run: make test
