apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.scanner.saName }}
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openvas-discovery
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods","endpoints","services"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openvas-discovery
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.scanner.saName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: openvas-discovery
  apiGroup: rbac.authorization.k8s.io
